# Generated by Django 4.1.2 on 2022-11-01 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stadium",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("capacity", models.IntegerField()),
                ("localizations", models.CharField(max_length=255)),
                ("area", models.FloatField()),
                (
                    "team_owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stadiums",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
