# Generated by Django 4.1.2 on 2022-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadiums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
