# Generated by Django 4.1.2 on 2022-11-01 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("age", models.PositiveIntegerField()),
                ("biography", models.TextField(max_length=500)),
                ("number_of_titles", models.PositiveIntegerField()),
                ("hometown", models.CharField(max_length=50)),
                ("current_team", models.CharField(max_length=50)),
            ],
        ),
    ]
