# Generated by Django 4.1.2 on 2022-11-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championship",
            name="games",
        ),
        migrations.RemoveField(
            model_name="championship",
            name="teams",
        ),
    ]
